### ISSUE TITLE
Enable HTTPS on smocks

### ISSUE THREAD

**Issue by abhagupta** [jhudson8/smocks#14]
Can Smocks provide availability of `https` along with `http` ?  This would mean the smocks will have to open 2  `hapi` connections, one listening on `http` and other on `https` for different ports. Currently, there is only one connection that is opened by smocks in hapi. We can open > 1 connection using smocks plugin option on external hapi instance as mentioned in docs, but support for `https` out-of-box might increase the usage of smocks to secured mocked api which is a huge use case.

**Comment by jhudson8** [comment]
just export smocks as a HAPI plugin and use your own HAPI HTTPS config with a self signed cert
