### ISSUE TITLE
Upgrade to smocks version 4.*.* breaks shifu admin

### ISSUE THREAD

**Issue by abhagupta** [jhudson8/smocks#18]
@walmart/shifu is an internal project which can be accessed via https://gecgithub01.walmart.com/otto/shifu .    The server starts up fine but when admin console is accessed using `http://dev.walmart.com:8080/_admin`, the issue is seen with babel. Here are some stack logs  
`exports.default (/Users/agupt13/Documents/workspace/mocks/shifu/node_modules/babel-template/lib/index.js:19:27),Object.<anonymous> (/Users/agupt13/Documents/workspace/mocks/shifu/node_modules/babel-helpers/lib/helpers.js:17:70),Module._compile (module.js:541:32),Object.Module._extensions..js (module.js:550:10),Module.load (module.js:458:32),tryModuleLoad (module.js:417:12),Function.Module._load (module.js:409:3),Module.require (module.js:468:17),require (internal/module.js:20:19),Object.<anonymous> (/Users/agupt13/Documents/workspace/mocks/shifu/node_modules/babel-helpers/lib/index.js:12:40),Module._compile (module.js:541:32),Object.Module._extensions..js (module.js:550:10),Module.load (module.js:458:32),tryModuleLoad (module.js:417:12),Function.Module._load (module.js:409:3),Module.require (module.js:468:17)`

Note that when smocks is executed on its own,  admin console is accessed successfully.

**Comment by jhudson8** [comment]
Given the details, I'm not exactly sure why this would break but I suspect it's related to this commit.

https://github.com/jhudson8/smocks/commit/cf9b94fd5f0ee5fb1790b4bc758f45b9964280f9

Still trying to figure out what to do about it though...

**Comment by abhagupta** [comment]
Hi @jhudson8 . Shifu is walmart's internal project. The repo is https://gecgithub01.walmart.com/otto/shifu.  The best way to reproduce is to
-  clone the source of shifu in your machine, 
- `npm install`. This will install `smocks` as dependency, but it will be version 3.2.1 
- run `npm run start-mock`
- visit `http://localhost:8080:/_admin` and you should be able to visit smocks admin.

Now to reproduce the issue,  change the version of smocks to `latest` in shifu's package .json, and do an `npm install` which should get the latest version of smocks (4.0.7). If you visit the admin url again, it will break with error i mentioned above.

 I have been cloning smocks locally and doing an `npm link` with shifu to troubleshoot on my system.

Thanks for looking into this.  (My node version is v5.11.0 and npm version is 3.9.2).

**Comment by abhagupta** [comment]
Closing this issue, since its fixed from shifu side
